import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  appShell: {
    flex: 1,
  },
  onboardingScreen: {
    backgroundColor: '#63b4f2',
    flex: 1,
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingHorizontal: 28,
    paddingVertical: 40,
    position: 'relative',
  },
  onboardingBackgroundOrbLarge: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 999,
    height: 280,
    position: 'absolute',
    right: -90,
    top: -40,
    width: 280,
  },
  onboardingBackgroundOrbSmall: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    height: 132,
    left: -24,
    position: 'absolute',
    top: 138,
    width: 132,
  },
  onboardingHero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  onboardingBrand: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: '800',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  onboardingCopyWrap: {
    alignItems: 'center',
    gap: 6,
    marginTop: 34,
  },
  onboardingHeadlineTop: {
    color: '#ffffff',
    fontSize: 26,
    fontWeight: '700',
    letterSpacing: -0.4,
    lineHeight: 34,
    textAlign: 'center',
  },
  onboardingHeadlineBottom: {
    color: '#f8fbff',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.6,
    lineHeight: 36,
    textAlign: 'center',
  },
  onboardingActionWrap: {
    gap: 12,
    paddingBottom: 10,
  },
  onboardingPrimaryButton: {
      alignItems: 'center',
      backgroundColor: '#f8fbff',
      borderRadius: 20,
      justifyContent: 'center',
      minHeight: 56,
      shadowColor: '#2e6f99',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
  },
  onboardingPrimaryButtonText: {
      color: '#2d6d98',
      fontSize: 15,
      fontWeight: '800',
  },
  onboardingSecondaryButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  onboardingSecondaryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  authScreen: {
    flex: 1,
    paddingHorizontal: 28,
    paddingVertical: 24,
  },
  authTopBar: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  authBackButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  authBody: {
    flex: 1,
    justifyContent: 'center',
  },
  authBrand: {
    color: '#eaf6ff',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.4,
    marginBottom: 20,
  },
  authHeading: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: -0.6,
  },
  authDescription: {
    color: '#edf7ff',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 280,
  },
  authButtonGroup: {
    gap: 12,
    marginTop: 32,
  },
  authPrimaryButton: {
    alignItems: 'center',
    borderRadius: 20,
    justifyContent: 'center',
    minHeight: 56,
  },
  authPrimaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  authOutlineButton: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 56,
  },
  authOutlineButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  authGhostButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    marginTop: 4,
  },
  authGhostButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  container: {
    gap: 18,
    paddingBottom: 120,
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  resultsContainer: {
    gap: 18,
    paddingBottom: 148,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  goalHubContainer: {
    gap: 18,
    paddingBottom: 148,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  detailContainer: {
    gap: 16,
    paddingBottom: 148,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  compareContainer: {
    gap: 16,
    paddingBottom: 148,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  myPageContainer: {
    gap: 16,
    paddingBottom: 148,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  myPageHeader: {
    gap: 6,
  },
  myPageHeaderDescription: {
    fontSize: 13,
    lineHeight: 19,
  },
  myProfileCard: {
    borderRadius: 26,
    borderWidth: 1,
    gap: 16,
    padding: 20,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
  },
  myProfileTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  myProfileAvatar: {
    alignItems: 'center',
    borderRadius: 22,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  myProfileAvatarText: {
    color: '#63b4f2',
    fontSize: 22,
    fontWeight: '800',
  },
  myProfileTextWrap: {
    flex: 1,
    gap: 4,
  },
  myProfileName: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  myProfileMeta: {
    fontSize: 12,
    lineHeight: 18,
  },
  myProfileEditButton: {
    alignItems: 'center',
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  myProfileRateText: {
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  myProfileGoalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  myProfileActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  myProfileGoalChip: {
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  myProfileGoalText: {
    fontSize: 12,
    fontWeight: '700',
  },
  myProfileActionLink: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
  },
  myProfileActionText: {
    fontSize: 12,
    fontWeight: '700',
  },
  myProfileActionDivider: {
    fontSize: 11,
    fontWeight: '600',
  },
  myQuickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  myQuickCard: {
    borderRadius: 20,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 8,
    minHeight: 124,
    padding: 16,
  },
  myQuickIconWrap: {
    alignItems: 'center',
    borderRadius: 16,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  myQuickTitle: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 21,
  },
  myQuickMeta: {
    fontSize: 12,
    lineHeight: 17,
  },
  mySettingList: {
    gap: 0,
  },
  mySettingRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
    paddingVertical: 16,
  },
  mySettingTextWrap: {
    flex: 1,
    gap: 4,
  },
  mySettingTitle: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  mySettingMeta: {
    fontSize: 12,
    lineHeight: 17,
  },
  intakeContainer: {
    gap: 16,
    paddingBottom: 148,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  intakeHeroHeader: {
    gap: 6,
  },
  intakeHeroDescription: {
    fontSize: 13,
    lineHeight: 19,
  },
  intakeSectionToggle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  intakeCollapsedHint: {
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  intakeChecklist: {
    gap: 10,
  },
  intakeChecklistItem: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 12,
  },
  intakeChecklistLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
  },
  intakeChecklistTextWrap: {
    flex: 1,
    gap: 3,
  },
  intakeChecklistName: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 21,
  },
  intakeChecklistTime: {
    fontSize: 12,
    fontWeight: '600',
  },
  intakeCheckbox: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  intakeSummaryCard: {
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
  },
  intakeSummaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  intakeSummaryItem: {
    flex: 1,
    gap: 6,
  },
  intakeSummaryLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  intakeSummaryValue: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  intakeSummaryDivider: {
    height: 28,
    width: 1,
  },
  intakeSlotList: {
    gap: 4,
  },
  intakeSlotCard: {
    gap: 14,
    paddingBottom: 16,
    paddingTop: 8,
  },
  intakeSlotHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  intakeSlotTitleWrap: {
    gap: 4,
  },
  intakeSlotTitle: {
    fontSize: 17,
    fontWeight: '800',
  },
  intakeSlotTime: {
    fontSize: 13,
    fontWeight: '600',
  },
  intakeSlotStatus: {
    fontSize: 12,
    fontWeight: '800',
  },
  intakeSupplementRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  intakeSupplementChip: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  intakeSupplementEmoji: {
    fontSize: 16,
  },
  intakeSupplementChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  intakeActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  intakeActionButton: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  intakeActionButtonText: {
    fontSize: 13,
    fontWeight: '800',
  },
  intakeSavedList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  intakeSavedItem: {
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 6,
    minHeight: 76,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  intakeSavedTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  intakeSavedName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
  },
  intakeSavedMeta: {
    fontSize: 12,
    fontWeight: '600',
  },
  intakeModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(17,17,17,0.26)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  intakeModalCard: {
    borderRadius: 28,
    borderWidth: 1,
    maxHeight: '72%',
    paddingHorizontal: 18,
    paddingVertical: 18,
    width: '100%',
  },
  intakeModalHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  intakeModalHeaderText: {
    flex: 1,
    gap: 4,
  },
  intakeModalClose: {
    alignItems: 'center',
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  intakeModalScroll: {
    marginTop: 6,
  },
  intakeModalList: {
    gap: 14,
    paddingBottom: 6,
  },
  intakeModalItem: {
    borderBottomWidth: 1,
    gap: 10,
    paddingBottom: 14,
  },
  intakeModalItemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  intakeTwiceButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 32,
    paddingHorizontal: 12,
  },
  intakeTwiceButtonText: {
    fontSize: 11,
    fontWeight: '800',
  },
  intakeScheduleEditor: {
    gap: 10,
  },
  intakeScheduleEditorLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
  intakePeriodChoiceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  intakePeriodChoice: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  intakePeriodChoiceText: {
    fontSize: 12,
    fontWeight: '700',
  },
  intakeTimeChoiceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  intakeTimeChoice: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  intakeTimeChoiceText: {
    fontSize: 12,
    fontWeight: '700',
  },
  intakeCalendarLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  intakeLegendItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  intakeLegendDot: {
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  intakeLegendText: {
    fontSize: 11,
    fontWeight: '600',
  },
  intakeCalendarWeekdays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  intakeCalendarWeekday: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  intakeCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  intakeCalendarCell: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '12.3%',
  },
  intakeCalendarDay: {
    aspectRatio: 1,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 38,
  },
  intakeCalendarDayText: {
    fontSize: 12,
    fontWeight: '800',
  },
  intakeMonthlySummaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  intakeMonthlySummaryCard: {
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  intakeMonthlySummaryLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
  intakeMonthlySummaryValue: {
    fontSize: 17,
    fontWeight: '800',
  },
  ingredientScreenEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  ingredientHeroHeader: {
    gap: 10,
  },
  ingredientHeroGoalPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  ingredientHeroGoalText: {
    fontSize: 12,
    fontWeight: '700',
  },
  ingredientHeroMetaRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    marginTop: 2,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  ingredientHeroMetaItem: {
    flex: 1,
    gap: 6,
  },
  ingredientHeroMetaItemCompact: {
    flex: 1,
    gap: 4,
  },
  ingredientHeroMetaDivider: {
    height: 30,
    width: 1,
  },
  ingredientHeroMetaLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  ingredientHeroMetaValue: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  ingredientSectionHeader: {
    gap: 10,
    marginTop: 6,
  },
  ingredientSectionEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  ingredientSectionLine: {
    borderRadius: 999,
    height: 1,
    width: 74,
  },
  personalChoiceChip: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  personalModeList: {
    gap: 10,
  },
  personalModeCard: {
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  personalModeIconWrap: {
    alignItems: 'center',
    borderRadius: 16,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  personalModeTextWrap: {
    flex: 1,
    gap: 3,
  },
  personalModeTitle: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  personalModeDescription: {
    fontSize: 12,
    lineHeight: 18,
  },
  personalOptionList: {
    gap: 10,
  },
  personalOptionRow: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  personalOptionTextWrap: {
    flex: 1,
  },
  personalOptionTitle: {
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  personalCheckCircle: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  personalSegmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  personalSegment: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '31%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 56,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  personalSegmentText: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'center',
  },
  personalCurrentWrap: {
    gap: 12,
    marginTop: 6,
  },
  personalCurrentLabel: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  personalSupplementFrame: {
    maxHeight: 188,
  },
  personalSupplementGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingRight: 2,
  },
  personalResultCard: {
    borderRadius: 28,
    borderWidth: 1,
    gap: 10,
    padding: 20,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
  },
  personalResultTitle: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.3,
    lineHeight: 30,
  },
  personalResultDescription: {
    fontSize: 14,
    lineHeight: 21,
  },
  personalHelperText: {
    fontSize: 12,
    lineHeight: 18,
  },
  personalRecommendationList: {
    gap: 10,
    marginTop: 2,
  },
  personalInsightGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  personalInsightCard: {
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minHeight: 82,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  personalInsightLabel: {
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
  },
  personalInsightValue: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  personalRecommendationItem: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  personalRecommendationTextWrap: {
    flex: 1,
    gap: 3,
  },
  personalRecommendationTitle: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  personalRecommendationNote: {
    fontSize: 12,
    lineHeight: 18,
  },
  topBar: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'space-between',
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  brand: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  topBarActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  themeToggle: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  searchHero: {
    borderRadius: 30,
    borderWidth: 1,
    gap: 10,
    padding: 22,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 33,
  },
  heroDescription: {
    fontSize: 13,
    lineHeight: 18,
  },
  searchBox: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
  },
  searchInlineButton: {
    alignItems: 'center',
    borderRadius: 14,
    justifyContent: 'center',
    minWidth: 64,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  searchInlineButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  resultsTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultsBackButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    marginLeft: -4,
    width: 34,
  },
  resultsHeaderTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
    marginLeft: 4,
  },
  resultsCartButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    position: 'relative',
    width: 36,
  },
  resultsCartBadge: {
    alignItems: 'center',
    borderRadius: 10,
    height: 20,
    justifyContent: 'center',
    minWidth: 20,
    position: 'absolute',
    right: -3,
    top: -1,
  },
  resultsCartBadgeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  resultsHeaderBlock: {
    gap: 2,
  },
  resultsQueryTitle: {
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  resultsQueryMeta: {
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
  },
  resultsScopeRow: {
    flexDirection: 'row',
    gap: 18,
    marginTop: 8,
  },
  resultsScopeTab: {
    gap: 6,
    paddingBottom: 4,
  },
  resultsScopeText: {
    fontSize: 12,
  },
  resultsScopeUnderline: {
    borderRadius: 999,
    height: 3,
    width: '100%',
  },
  resultsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
    marginTop: 4,
  },
  resultsList: {
    gap: 0,
  },
  resultListRow: {
    alignItems: 'center',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 14,
  },
  resultListRowLast: {
    borderBottomWidth: 0,
  },
  resultListVisual: {
    alignItems: 'center',
    borderRadius: 18,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  resultListContent: {
    flex: 1,
    gap: 3,
  },
  resultListBrand: {
    fontSize: 11,
    fontWeight: '700',
  },
  resultListTitle: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  resultListSummary: {
    fontSize: 12,
    lineHeight: 17,
  },
  resultListMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  resultListMetaValue: {
    fontSize: 13,
    fontWeight: '800',
  },
  resultListTotal: {
    fontSize: 12,
    fontWeight: '600',
  },
  resultListAction: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  resultGridItem: {
    flexBasis: '47%',
    flexGrow: 1,
    gap: 10,
  },
  ingredientProductVisualBoard: {
    alignItems: 'center',
    borderRadius: 20,
    height: 164,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  ingredientProductEmoji: {
    fontSize: 38,
  },
  ingredientProductBadge: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    bottom: 12,
    height: 36,
    justifyContent: 'center',
    left: 12,
    position: 'absolute',
    width: 36,
  },
  resultVisualBoard: {
    alignItems: 'center',
    borderRadius: 24,
    height: 184,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  resultVisualShape: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
  },
  resultEmoji: {
    fontSize: 28,
  },
  resultEmojiLarge: {
    fontSize: 42,
  },
  resultBadge: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    bottom: 14,
    height: 40,
    justifyContent: 'center',
    left: 14,
    position: 'absolute',
    width: 40,
  },
  resultGridTitle: {
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 23,
  },
  resultGridSummary: {
    fontSize: 12,
    lineHeight: 18,
    minHeight: 34,
  },
  resultDivider: {
    height: 1,
    width: '100%',
  },
  resultPriceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultPriceLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
  resultGridPrice: {
    fontSize: 16,
    fontWeight: '800',
  },
  resultGridTotal: {
    fontSize: 12,
    fontWeight: '600',
  },
  resultActionButton: {
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 46,
  },
  resultActionButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  ingredientProductAction: {
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 44,
  },
  goalHubHeader: {
    gap: 6,
  },
  goalHubStickyTabs: {
    marginHorizontal: -24,
    paddingBottom: 8,
    paddingHorizontal: 24,
    paddingTop: 4,
  },
  goalHubTabRow: {
    gap: 10,
    paddingRight: 24,
  },
  goalHubTabChip: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  goalHubTabText: {
    fontSize: 13,
  },
  goalHubTitle: {
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  goalHubMeta: {
    fontSize: 13,
    fontWeight: '600',
  },
  goalHubGrid: {
    gap: 10,
  },
  goalHubList: {
    gap: 10,
  },
  goalHubListRow: {
    alignItems: 'center',
    borderBottomWidth: 1,
    borderRadius: 18,
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 2,
    paddingVertical: 16,
  },
  goalHubListVisual: {
    alignItems: 'center',
    borderRadius: 20,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  goalHubEmoji: {
    fontSize: 30,
  },
  goalHubListContent: {
    flex: 1,
    gap: 4,
  },
  goalHubListTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  goalHubListDescription: {
    fontSize: 12,
    lineHeight: 17,
  },
  goalHubListPrice: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  goalHubListArrowWrap: {
    alignItems: 'center',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  goalHubCard: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  goalHubVisualBoard: {
    alignItems: 'center',
    borderRadius: 22,
    height: 148,
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  goalHubVisualShape: {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
  },
  goalHubBadge: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    bottom: 12,
    height: 36,
    justifyContent: 'center',
    left: 12,
    position: 'absolute',
    width: 36,
  },
  goalHubContent: {
    gap: 6,
  },
  goalHubCardText: {
    fontSize: 18,
    fontWeight: '800',
  },
  goalHubCardDescription: {
    fontSize: 13,
    lineHeight: 19,
  },
  goalHubCardPrice: {
    fontSize: 12,
    fontWeight: '700',
  },
  section: {
    borderRadius: 28,
    borderWidth: 1,
    gap: 12,
    padding: 20,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
  },
  sectionLink: {
    fontSize: 12,
    fontWeight: '700',
  },
  goalGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingBottom: 10,
    paddingRight: 2,
  },
  goalScrollShell: {
    position: 'relative',
  },
  goalScrollFrame: {
    maxHeight: 194,
  },
  goalChip: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 54,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  goalChipText: {
    fontSize: 14,
    fontWeight: '700',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  categoryCard: {
    borderRadius: 22,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 5,
    padding: 14,
  },
  categoryTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  categoryIconWrap: {
    alignItems: 'center',
    borderRadius: 14,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  categoryMeta: {
    fontSize: 11,
  },
  brandGrid: {
    gap: 10,
  },
  brandEntry: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  brandEntryTextWrap: {
    flex: 1,
    gap: 4,
  },
  brandEntryTitle: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  brandEntryMeta: {
    fontSize: 12,
    lineHeight: 18,
  },
  brandCard: {
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  brandMark: {
    alignItems: 'center',
    borderRadius: 16,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  brandMarkText: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  brandTextWrap: {
    flex: 1,
    gap: 3,
  },
  brandLabel: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  brandMeta: {
    fontSize: 12,
    lineHeight: 17,
  },
  detailTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  backButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  detailTopTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  detailTopActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  detailHero: {
    borderRadius: 28,
    borderWidth: 1,
    gap: 18,
    padding: 22,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
  },
  detailVisual: {
    alignItems: 'center',
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    paddingVertical: 28,
  },
  detailVisualBadge: {
    alignItems: 'center',
    borderRadius: 24,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  detailVisualText: {
    fontSize: 12,
    fontWeight: '600',
  },
  detailIntro: {
    gap: 6,
  },
  detailBrand: {
    fontSize: 13,
    fontWeight: '700',
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  detailSubtitle: {
    fontSize: 14,
    lineHeight: 20,
  },
  detailPriceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  detailPrice: {
    fontSize: 26,
    fontWeight: '800',
  },
  priceTag: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  priceTagText: {
    fontSize: 12,
    fontWeight: '700',
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: '600',
  },
  detailSection: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  ingredientPairingSection: {
    borderTopWidth: 1,
    gap: 14,
    marginTop: 6,
    paddingTop: 18,
  },
  highlightList: {
    gap: 12,
  },
  highlightRow: {
    borderBottomWidth: 1,
    gap: 6,
    paddingBottom: 12,
  },
  highlightLabel: {
    fontSize: 12,
    fontWeight: '700',
  },
  highlightValue: {
    fontSize: 16,
    fontWeight: '700',
  },
  ingredientGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  ingredientChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  ingredientChipText: {
    fontSize: 13,
    fontWeight: '700',
  },
  checkList: {
    gap: 12,
  },
  checkRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  checkText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  detailActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  detailSecondaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 18,
  },
  detailSecondaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
  },
  detailPrimaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 18,
  },
  detailPrimaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
  },
  compareHero: {
    borderRadius: 24,
    borderWidth: 1,
    gap: 8,
    padding: 18,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  compareHeroTitle: {
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 28,
  },
  compareHeroText: {
    fontSize: 13,
    lineHeight: 19,
  },
  compareCardRow: {
    gap: 12,
    paddingRight: 6,
  },
  compareProductCard: {
    borderRadius: 22,
    borderWidth: 1,
    gap: 6,
    padding: 16,
    width: 210,
  },
  compareProductBrand: {
    fontSize: 12,
    fontWeight: '700',
  },
  compareProductName: {
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
  },
  compareProductPrice: {
    fontSize: 20,
    fontWeight: '800',
    marginTop: 2,
  },
  compareProductMeta: {
    fontSize: 12,
    lineHeight: 17,
  },
  compareTable: {
    borderRadius: 20,
    borderWidth: 1,
    overflow: 'hidden',
  },
  compareHeaderRow: {
    borderBottomWidth: 1,
    flexDirection: 'row',
  },
  compareDataRow: {
    borderBottomWidth: 1,
    flexDirection: 'row',
  },
  compareLabelCell: {
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 14,
    width: 96,
  },
  compareValueCell: {
    justifyContent: 'center',
    minHeight: 58,
    paddingHorizontal: 14,
    width: 148,
  },
  compareHeaderLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  compareRowLabel: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  compareRowValue: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  bottomBar: {
    borderBottomWidth: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    gap: 8,
    left: 0,
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 14,
    position: 'absolute',
    right: 0,
  },
  tabItem: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
    paddingVertical: 12,
  },
  tabIcon: {
    marginBottom: 1,
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: '600',
  },
  tabLabelActive: {
    fontWeight: '800',
  },
});
